# Generated by Django 2.0.13 on 2019-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propuestas',
            fields=[
                ('IdPropuestas', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('PropuestaNombre', models.CharField(max_length=500)),
                ('PropuestaDetalle', models.TextField(max_length=1000)),
                ('Votos', models.IntegerField(default=0)),
            ],
        ),
    ]
