# Generated by Django 2.0.13 on 2019-06-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Votos', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='propuestas',
            name='Votos',
        ),
        migrations.AddField(
            model_name='votos',
            name='IdVoto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.Propuestas'),
        ),
    ]
