# Generated by Django 2.0.13 on 2019-06-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_auto_20190619_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votos',
            name='IdVoto',
        ),
        migrations.AddField(
            model_name='propuestas',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='propuestas',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='propuestas',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.DeleteModel(
            name='Votos',
        ),
    ]
