# Generated by Django 2.0.13 on 2019-07-04 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0004_auto_20190625_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('codigo_taller', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 7, 4, 0, 53, 41, 681215))),
                ('lugar_taller', models.CharField(max_length=60)),
            ],
        ),
    ]
