# Generated by Django 2.0.13 on 2019-07-09 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0006_auto_20190709_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 14, 31, 54, 720734)),
        ),
    ]
