# Generated by Django 2.0.13 on 2019-07-09 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0007_auto_20190709_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('IdPropuesta', models.AutoField(primary_key=True, serialize=False)),
                ('PropuestaNombre', models.CharField(max_length=500)),
                ('PropuestaDetalle', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PropuestaAprobada',
            fields=[
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('IdPropuestaAprobada', models.AutoField(primary_key=True, serialize=False)),
                ('PropuestaAprobadaNombre', models.CharField(max_length=500)),
                ('PropuestaAprobadaDetalle', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Propuestas',
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 14, 34, 24, 599645)),
        ),
    ]
